name: horror_stories
description: UI for board game

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-21.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # BLoC
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  path_provider: ^2.0.12

  #UI
  loading_animation_widget: ^1.2.0+4
  flutter_svg: ^2.0.2
  bot_toast: ^4.0.3
  flip_card: ^0.7.0

  #backend
  dio: ^5.0.1
  equatable: ^2.0.5

  #storage
  hive: ^2.2.3

  # DI
  get_it: ^7.2.0
  injectable: ^2.1.0

  # Navigation
  go_router: ^6.2.0

  # Other
  uuid: ^3.0.7
  logger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.3.3
  json_annotation: ^4.3.0
  json_serializable: ^6.5.4
  freezed: ^2.3.2
  injectable_generator: ^2.1.4

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/raster/
    - assets/raster/cards/
    - assets/vector/figma_icons/
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
    - family: Yeseva One
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
