DROP TABLE IF EXISTS Masters;

CREATE TABLE IF NOT EXISTS Masters (
  playerId INT,
  PRIMARY KEY (playerId),
  FOREIGN KEY (playerId) REFERENCES Players(playerId) ON UPDATE CASCADE ON DELETE CASCADE 
);