DROP TABLE IF EXISTS Moves;
CREATE TABLE IF NOT EXISTS Moves (
roomCode INT UNSIGNED PRIMARY KEY, 
roundNumber TINYINT UNSIGNED NOT NULL DEFAULT 1, 
phase ENUM('voting', 'hints') NOT NULL DEFAULT 'hints',
startedAt TIMESTAMP NOT NULL
)