DROP TABLE IF EXISTS Moves;

CREATE TABLE IF NOT EXISTS Moves (
  roomCode INT UNSIGNED,
  roundNumber TINYINT UNSIGNED NOT NULL DEFAULT 1, 
  phase ENUM('voting', 'hints') NOT NULL DEFAULT 'hints',
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (roomCode),
  FOREIGN KEY (roomCode) REFERENCES Rooms(roomCode) ON UPDATE CASCADE ON DELETE CASCADE
);