DROP TABLE IF EXISTS Players;
CREATE TABLE IF NOT EXISTS Players (
playerId INT PRIMARY KEY AUTO_INCREMENT, 
login VARCHAR(30) NOT NULL  REFERENCES Users(login) ON UPDATE CASCADE ON DELETE CASCADE, 
roomCode INT UNSIGNED NOT NULL REFERENCES Rooms(roomCode) ON UPDATE CASCADE ON DELETE CASCADE,
UNIQUE (login, roomCode)
)