DROP TABLE IF EXISTS Players;

CREATE TABLE IF NOT EXISTS Players (
    playerId INT PRIMARY KEY AUTO_INCREMENT, 
    login VARCHAR(30) NOT NULL, 
    roomCode INT UNSIGNED NOT NULL,
    UNIQUE (login, roomCode),
    FOREIGN KEY (login) REFERENCES Users(login) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (roomCode) REFERENCES Rooms(roomCode) ON UPDATE CASCADE ON DELETE CASCADE
);