DROP TABLE IF EXISTS TableCards;
CREATE TABLE IF NOT EXISTS TableCards (
tableCardId INT PRIMARY KEY AUTO_INCREMENT, 
roomCode INT UNSIGNED NOT NULL REFERENCES Rooms(roomCode) ON UPDATE CASCADE ON DELETE CASCADE, 
cardName VARCHAR(25) NOT NULL REFERENCES Cards(cardName) ON UPDATE CASCADE, 
isOnTable TINYINT NOT NULL DEFAULT '1',
UNIQUE (roomCode, cardName)
)