DROP TABLE IF EXISTS Tokens;

CREATE TABLE IF NOT EXISTS Tokens (
    login VARCHAR(30) PRIMARY KEY, 
    token VARCHAR(50) NOT NULL UNIQUE,
    refreshToken VARCHAR(50) NOT NULL UNIQUE,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (login) REFERENCES Users(login) ON UPDATE CASCADE ON DELETE CASCADE
);