DROP TABLE IF EXISTS Votes;
CREATE TABLE IF NOT EXISTS Votes (
    playerId INT REFERENCES Players(playerId) ON UPDATE CASCADE ON DELETE CASCADE, 
    tableCardId INT REFERENCES TableCards(tableCardId) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (playerId, tableCardId)
)